<?php

use App\Core\Csrf;
use App\Core\View;

$hasProfileImage = !empty($user['profile_image_path']);
$initial = strtoupper(substr((string) $user['username'], 0, 1));
?>
<section class="page-heading"><div><p class="page-eyebrow">Account</p><h1>Profile</h1><p class="page-subtitle">Manage your identity, contact details, and profile picture.</p></div></section>
<?php foreach ($errors as $error): ?><div class="app-flash flash-error"><i class="bi bi-exclamation-circle-fill"></i><?= View::e($error) ?></div><?php endforeach; ?>
<section class="form-panel form-panel-wide"><form method="post" enctype="multipart/form-data" action="<?= View::e($baseUrl) ?>/profile"><input type="hidden" name="_csrf" value="<?= View::e(Csrf::token()) ?>"><div class="row g-4"><div class="col-12"><div class="profile-picture-editor"><div class="profile-picture-preview"><?php if ($hasProfileImage): ?><img src="<?= View::e($baseUrl) ?>/profile/photo" alt="Current profile picture"><?php else: ?><span><?= View::e($initial) ?></span><?php endif; ?></div><div><h2>Profile Picture</h2><p class="text-muted mb-2">Upload a photo to show it in the top-right account menu.</p><label class="form-label" for="profile_image">Choose picture</label><input class="form-control" id="profile_image" type="file" name="profile_image" accept="image/jpeg,image/png,image/webp"><div class="form-text">JPG, PNG, or WebP. Maximum 5 MB.</div><?php if ($hasProfileImage): ?><div class="form-check mt-2"><input class="form-check-input" id="remove_profile_image" type="checkbox" name="remove_profile_image"><label class="form-check-label" for="remove_profile_image">Remove current picture</label></div><?php endif; ?></div></div></div><div class="col-12"><label class="form-label" for="full_name">Full Name</label><input class="form-control" id="full_name" name="full_name" maxlength="100" value="<?= View::e($user['full_name'] ?? '') ?>" placeholder="Your full name"></div><div class="col-md-6"><label class="form-label" for="username">Username</label><input class="form-control" id="username" name="username" required value="<?= View::e($user['username']) ?>"></div><div class="col-md-6"><label class="form-label" for="email">Email</label><input class="form-control" id="email" name="email" type="email" required value="<?= View::e($user['email']) ?>"></div></div><div class="form-actions"><button class="btn btn-primary"><i class="bi bi-check2-circle"></i> Save Profile</button></div></form></section>
